import type {
  Apartment, Unit, ExternalApartment, Booking, Payment, Promotion,
  ExternalUserProfile, InternalUserProfile
} from '../types';

export const INITIAL_APARTMENTS: Apartment[] = [
  {
    apartmentId: 'APT-ORA-01',
    name: 'Living-Ora Heights & Sky Residences',
    location: '75 Marina Boulevard, Coastal Towers, Colombo 03',
    numOfRoom: 120,
    numOfFloors: 35,
    numOfSwimmingPool: 2,
    numOfGYM: 1,
    images: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    about: 'Living-Ora Heights stands as an architectural masterpiece along the coastline. Featuring panoramic ocean views, infinity pools, smart home automation, and 24/7 concierge service.',
    floorPlan: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    numOfUnitsAvilable: 18,
    priceRange: '$220,000 - $850,000',
    unitStatus: 'Available',
    promotion_id: 'PROMO-SUMMER2026',
    internalUser_empId: 'EMP-1002',
  },
  {
    apartmentId: 'APT-ORA-02',
    name: 'Living-Ora Royal Pinnacle',
    location: '12 Park Avenue, Cinnamon Gardens, Colombo 07',
    numOfRoom: 85,
    numOfFloors: 24,
    numOfSwimmingPool: 1,
    numOfGYM: 1,
    images: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    about: 'Ultra-luxury sanctuary in the heart of Cinnamon Gardens. Designed for privacy, green living, and high-yielding real estate investment.',
    floorPlan: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    numOfUnitsAvilable: 12,
    priceRange: '$350,000 - $1,200,000',
    unitStatus: 'Available',
    promotion_id: 'PROMO-EARLYBIRD',
    internalUser_empId: 'EMP-1001',
  },
  {
    apartmentId: 'APT-ORA-03',
    name: 'Living-Ora Eco Urban Oasis',
    location: '44 Green Way, Nawala Waterfront',
    numOfRoom: 60,
    numOfFloors: 16,
    numOfSwimmingPool: 1,
    numOfGYM: 1,
    images: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    about: 'Sustainable urban living featuring solar-powered energy, rooftop garden lounges, and direct lake views.',
    floorPlan: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80',
    numOfUnitsAvilable: 8,
    priceRange: '$180,000 - $490,000',
    unitStatus: 'Available',
    promotion_id: null,
    internalUser_empId: 'EMP-1002',
  },
];

export const INITIAL_UNITS: Unit[] = [
  {
    unitId: 'UNT-101-A',
    apartment_id: 'APT-ORA-01',
    unitPrice: 280000,
    floor: 10,
    location: '10th Floor - Ocean Facing North',
    avilability: 'Available',
    fernitures: 'Fully Furnished',
    numOfBathRooms: 2,
    numOfRooms: 2,
    numOfBeds: 2,
    acOrNonAC: 'AC',
    reccomendedPerson: 'Small Family / Executives',
    about: 'Elegant 2-bedroom suite with floor-to-ceiling glass balconies overlooking the Indian Ocean.',
    images: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
  },
  {
    unitId: 'UNT-250-P',
    apartment_id: 'APT-ORA-01',
    unitPrice: 750000,
    floor: 25,
    location: '25th Floor - Penthouse East Wing',
    avilability: 'Available',
    fernitures: 'Semi-Furnished',
    numOfBathRooms: 4,
    numOfRooms: 4,
    numOfBeds: 4,
    acOrNonAC: 'AC',
    reccomendedPerson: 'VIP / Large Family',
    about: 'Exclusive duplex penthouse with private plunge pool, outdoor terrace, and designer kitchen.',
    images: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80',
  },
  {
    unitId: 'UNT-050-B',
    apartment_id: 'APT-ORA-02',
    unitPrice: 420000,
    floor: 5,
    location: '5th Floor - Garden View West',
    avilability: 'Available',
    fernitures: 'Unfurnished',
    numOfBathRooms: 3,
    numOfRooms: 3,
    numOfBeds: 3,
    acOrNonAC: 'AC',
    reccomendedPerson: 'Families',
    about: 'Spacious 3-bedroom apartment with custom teak wood flooring and spacious veranda.',
    images: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
  },
  {
    unitId: 'UNT-120-C',
    apartment_id: 'APT-ORA-02',
    unitPrice: 510000,
    floor: 12,
    location: '12th Floor - Pinnacle View',
    avilability: 'Reserved',
    fernitures: 'Fully Furnished',
    numOfBathRooms: 3,
    numOfRooms: 3,
    numOfBeds: 3,
    acOrNonAC: 'AC',
    reccomendedPerson: 'Investors / Expats',
    about: 'Luxury suite currently under reservation status for high-profile client.',
    images: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80',
  },
  {
    unitId: 'UNT-040-E',
    apartment_id: 'APT-ORA-03',
    unitPrice: 195000,
    floor: 4,
    location: '4th Floor - Lakefront View',
    avilability: 'Available',
    fernitures: 'Semi-Furnished',
    numOfBathRooms: 1,
    numOfRooms: 1,
    numOfBeds: 1,
    acOrNonAC: 'AC',
    reccomendedPerson: 'Single Professional',
    about: 'Modern studio loft designed for efficiency, green living, and high comfort.',
    images: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_EXTERNAL_APARTMENTS: ExternalApartment[] = [
  {
    exApartmentId: 'EXT-APT-901',
    location: '15 Temple Road, Mount Lavinia',
    about: 'Beachside 2-bedroom condominium with sea breeze access and private parking spot.',
    numOfRooms: 2,
    price: 160000,
    downPayment: 16000,
    images: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=800&q=80',
    acOrNonAC: 'AC',
    additionalInfo: 'Direct listing from owner. Title deeds clear.',
  },
  {
    exApartmentId: 'EXT-APT-902',
    location: '88 Main Street, Kandy Hills',
    about: 'Mountain view retreat apartment situated close to the scenic Kandy lake.',
    numOfRooms: 3,
    price: 210000,
    downPayment: 21000,
    images: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80',
    acOrNonAC: 'AC',
    additionalInfo: 'Includes solar backup power generator.',
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    promotionId: 'PROMO-EARLYBIRD',
    promotionType: 'Discount Code',
    promotionTitle: 'Early Bird 10% Off Reserve Special',
    about: 'Book any unit at Living-Ora Royal Pinnacle before the end of the month and save 10% on your initial down payment.',
    eligibilityCriteria: 'First-time buyers with minimum 20% down payment committed.',
    startDate: '2026-09-01',
    endDate: '2026-10-31',
    buttonText: 'Claim 10% Discount',
    bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    validityPeriod: 'Limited to 15 Units',
    discountPrecentage: 10.0,
    promotionCode: 'LIVINGORA10',
  },
  {
    promotionId: 'PROMO-SUMMER2026',
    promotionType: 'Furnishing Package',
    promotionTitle: 'Free Italian Luxury Furniture Package',
    about: 'All purchases for Living-Ora Heights ocean facing suites include a complimentary interior furnishing package valued at $25,000.',
    eligibilityCriteria: 'Applies to 2-Bedroom & Penthouse units.',
    startDate: '2026-08-15',
    endDate: '2026-11-30',
    buttonText: 'Explore Package',
    bannerImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    validityPeriod: 'Valid until Nov 30',
    discountPrecentage: 5.0,
    promotionCode: 'LUXFURNISH',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 1,
    bookingId: 'BKG-2026-089',
    uid: 'USR-EXT-5001',
    userName: 'Alexander Vance',
    userEmail: 'customer@livingora.com',
    unitId: 'UNT-120-C',
    unitLocation: 'Living-Ora Royal Pinnacle - Unit 120-C',
    bookingDate: '2026-09-02',
    expireDate: '2026-09-17',
    status: 'Pending Approval',
    additions: 'Requested custom marble kitchen island',
    payment_id: 101,
    paymentAmount: 510000,
    downPayment: 51000,
    paymentMethod: 'Bank Transfer',
    paymentProof: 'bank_receipt_transfer_892.pdf',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 101,
    paymentId: 'PAY-90481',
    bookingId: 'BKG-2026-089',
    paymentAmount: 51000,
    pendingAmount: 459000,
    paymentMethod: 'Bank Transfer',
    paymentProof: 'bank_receipt_transfer_892.pdf',
    dateAndTime: '2026-09-02T14:30:00Z',
    downPayment: 51000,
    numOfMonthsForPay: 36,
    status: 'Verification Pending',
  },
];

export const MOCK_USERS = {
  customer: {
    uid: 'USR-EXT-5001',
    email: 'customer@livingora.com',
    firstName: 'Alexander',
    lastName: 'Vance',
    role: 'EXTERNAL_USER',
    phoneNumber: '+94 77 123 4567',
    nic: '921849201V',
    address: '74 Crescent Road, Colombo 03',
    age: 34,
    profilePicture: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  } as ExternalUserProfile,
  staff: {
    empId: 'EMP-1002',
    email: 'staff@livingora.com',
    firstName: 'Samantha',
    lastName: 'Reynolds',
    role: 'INTERNAL_STAFF',
    companyEmail: 's.reynolds@livingora.com',
    phoneNumber: '+94 71 987 6543',
    nic: '887120491V',
    serviceYears: 6,
    profilePicture: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
  } as InternalUserProfile,
};
